/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Controller;
import logica.Usuario;

/**
 *
 * @author PedroD
 */
public class JFlogin extends javax.swing.JFrame {

    private final JFChat chat;
    private final JFRegistro registro;
    private Controller control;
    private final Icon icono = new ImageIcon(getClass().getResource("/resources/icono_informacion.png"));
    private Usuario user;
    private final JFconectando jfload = new JFconectando();

    /**
     * Get the value of user
     *
     * @return the value of user
     */
    public Usuario getUser() {
        return user;
    }

    /**
     * Set the value of user
     *
     * @param user new value of user
     */
    public void setUser(Usuario user) {
        this.user = user;
    }

    /**
     * Get the value of control
     *
     * @return the value of control
     */
    public Controller getControl() {
        return control;
    }

    /**
     * Set the value of control
     *
     * @param control new value of control
     */
    public void setControl(Controller control) {
        this.control = control;
    }

    /**
     * Creates new form JFNkickname
     *
     * @throws java.lang.Exception
     */
    public JFlogin() throws Exception {
        control = new Controller();
        this.user = new Usuario();
        this.chat = new JFChat();
        this.registro = new JFRegistro();
        initComponents();
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/1430109762_Orange forum.png"));
        chat.setIconImage(image);
        registro.setIconImage(image);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBloguear = new javax.swing.JButton();
        JLusername = new javax.swing.JLabel();
        JTXTusername = new javax.swing.JTextField();
        JLpass = new javax.swing.JLabel();
        JBregistrar = new javax.swing.JButton();
        JPFpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        setResizable(false);

        JBloguear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JBloguear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1430109558_go-next.png"))); // NOI18N
        JBloguear.setText("Loguear");
        JBloguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBloguearActionPerformed(evt);
            }
        });

        JLusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/man-42934_640.png"))); // NOI18N
        JLusername.setText("Nombre de Usuario");

        JTXTusername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JLpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLpass.setText("Contraseña");

        JBregistrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JBregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/adduser.png"))); // NOI18N
        JBregistrar.setText("Registrar nueva cuenta");
        JBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBregistrarActionPerformed(evt);
            }
        });

        JPFpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPFpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPFpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(JBloguear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLusername)
                            .addComponent(JLpass, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPFpass, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(JTXTusername))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLusername)
                    .addComponent(JTXTusername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLpass)
                    .addComponent(JPFpass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBloguear)
                    .addComponent(JBregistrar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBloguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBloguearActionPerformed

        if (!JTXTusername.getText().isEmpty() || JPFpass.getPassword().length > 0) {
            Icon icon = new ImageIcon(getClass().getResource("/resources/load.gif"));
            Icon icon1 = new ImageIcon(getClass().getResource("/resources/1430109558_go-next.png"));
            JBloguear.setIcon(icon);
            JBloguear.setRolloverIcon(icon);
            JBloguear.updateUI();
            JBloguear.repaint();
            this.validate();
            user.setUsername(JTXTusername.getText());
            user.setPassword(Arrays.toString(JPFpass.getPassword()));
            JFlogin aux = this;
            new Thread() {
                JFlogin aux1 = aux;

                @Override
                public void run() {
                    try {
                        if (control.verificaInternet()) {
                            switch (control.loguear(user)) {
                                case 1: {
                                    JBloguear.setIcon(icon1);
                                    JBloguear.setRolloverIcon(icon1);
                                    JBloguear.repaint();
                                    jfload.setVisible(false);
                                    chat.nickName(user.getNombre());
                                    chat.setUser(user);
                                    chat.setVisible(true);
                                    chat.start();
                                    aux1.setVisible(false);
                                    break;
                                }
                                case 2: {
                                    JBloguear.setIcon(icon1);
                                    JBloguear.setRolloverIcon(icon1);
                                    JBloguear.repaint();
                                    JOptionPane.showMessageDialog(rootPane, "Nombre de usuario incorrecto", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
                                    break;
                                }
                                case 3: {
                                    JBloguear.setIcon(icon1);
                                    JBloguear.setRolloverIcon(icon1);
                                    JBloguear.repaint();
                                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
                                    break;
                                }
                            }
                        } else {
                            JBloguear.setIcon(icon1);
                            JBloguear.setRolloverIcon(icon1);
                            JBloguear.repaint();
                            JOptionPane.showMessageDialog(rootPane, "Conexión con servidor no establecida, por favor revise su conexión y vuelva a intentar", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        //  Logger.getLogger(JFlogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite su nombre de usuario y contraseña", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
        }
    }//GEN-LAST:event_JBloguearActionPerformed

    private void JBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBregistrarActionPerformed
        this.dispose();
        registro.setVisible(true);
    }//GEN-LAST:event_JBregistrarActionPerformed

    private void JPFpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPFpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPFpassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBloguear;
    private javax.swing.JButton JBregistrar;
    private javax.swing.JLabel JLpass;
    private javax.swing.JLabel JLusername;
    private javax.swing.JPasswordField JPFpass;
    private javax.swing.JTextField JTXTusername;
    // End of variables declaration//GEN-END:variables
}
