/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Usuario;

/**
 *
 * @author PedroD
 */
public class JFRegistro extends javax.swing.JFrame {

    private final Icon icono = new ImageIcon(getClass().getResource("/resources/icono_informacion.png"));

    /**
     * Creates new form JFRegistro
     */
    public JFRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnombre = new javax.swing.JLabel();
        JLemail = new javax.swing.JLabel();
        JLusername = new javax.swing.JLabel();
        JLpassword = new javax.swing.JLabel();
        JTXTnombre = new javax.swing.JTextField();
        JTXTemail = new javax.swing.JTextField();
        JTXTusername = new javax.swing.JTextField();
        JBregistrar = new javax.swing.JButton();
        JBregresar = new javax.swing.JButton();
        JPFpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de nuevo usuario");

        JLnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLnombre.setText("Nombre ");

        JLemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLemail.setText("E-mail");

        JLusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLusername.setText("Nombre de usuario");

        JLpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLpassword.setText("Contraseña");

        JTXTnombre.setPreferredSize(new java.awt.Dimension(6, 27));

        JTXTemail.setPreferredSize(new java.awt.Dimension(6, 27));

        JTXTusername.setPreferredSize(new java.awt.Dimension(6, 27));

        JBregistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/adduser.png"))); // NOI18N
        JBregistrar.setText("Registrarse");
        JBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBregistrarActionPerformed(evt);
            }
        });

        JBregresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        JBregresar.setText("Regresar");
        JBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBregresarActionPerformed(evt);
            }
        });

        JPFpass.setPreferredSize(new java.awt.Dimension(6, 27));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/man-42934_640.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBregistrar)
                        .addGap(18, 18, 18)
                        .addComponent(JBregresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLnombre)
                            .addComponent(JLemail)
                            .addComponent(JLusername)
                            .addComponent(JLpassword))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTXTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JPFpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTXTusername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLnombre)
                            .addComponent(JTXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLemail)
                            .addComponent(JTXTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLusername)
                            .addComponent(JTXTusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLpassword)
                            .addComponent(JPFpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBregresar)
                    .addComponent(JBregistrar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBregistrarActionPerformed
        Usuario user = new Usuario();
        user.setNombre(JTXTnombre.getText());
        user.setEmail(JTXTemail.getText());
        user.setUsername(JTXTusername.getText());
        user.setPassword(Arrays.toString(JPFpass.getPassword()));
        System.out.println("user " + user.toString());
        try {

            switch (vista.Start.getNn().getControl().registarUsuario(user)) {
                case 1: {
                    JOptionPane.showMessageDialog(rootPane, "Registro completado, para entrar en el chat su nombre de usuario y su contraseña", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
                    JTXTemail.setText("");
                    JTXTnombre.setText("");
                    JTXTusername.setText("");
                    JPFpass.setText("");
                    break;
                }
                case 2: {
                    JOptionPane.showMessageDialog(rootPane, "Registro incompletado, nombre de usuario ya existe", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
                    break;
                }
                case 3: {
                    JOptionPane.showMessageDialog(rootPane, "Registro incompletado, e-mail ya existe", "Información", JOptionPane.INFORMATION_MESSAGE, icono);
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JFRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBregistrarActionPerformed

    private void JBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBregresarActionPerformed
        this.dispose();
        vista.Start.getNn().setVisible(true);
    }//GEN-LAST:event_JBregresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBregistrar;
    private javax.swing.JButton JBregresar;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLpassword;
    private javax.swing.JLabel JLusername;
    private javax.swing.JPasswordField JPFpass;
    private javax.swing.JTextField JTXTemail;
    private javax.swing.JTextField JTXTnombre;
    private javax.swing.JTextField JTXTusername;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
